### ISSUE TITLE
repo structure

### ISSUE THREAD

**Issue by ansuz** [hyperboria/peers#1]
```
README.md
creds/
  *.json
```

naming scheme?

**Comment by dansup** [comment]
I think using the nodes ipv6 address would suffice.    
    
For example:
``` peers/creds/fcec:ae97:8902:d810:6c92:ec67:efb2:3ec5.json ```

**Comment by ansuz** [comment]
If a few more people agree we'll go with that.

**Comment by dansup** [comment]
Actually, I don't think that is a valid file name. I propose to use the public key instead.

**Comment by thefinn93** [comment]
It should be based on region. IPv6 address is arbitrary, not something you look for with peering. What if we did like `peers/creds/<country>/<state|bioregion|city>/<pubkey>.json`

**Comment by ansuz** [comment]
oh, I like that

**Comment by dansup** [comment]
@thefinn93 I think that is good idea.

**Comment by ansuz** [comment]
nodeinfo.json has location fields now. those fields could then follow that same convention, and make peering suggestions easier.

**Comment by cschmittiey** [comment]
Sounds good to me

**Comment by ansuz** [comment]
So, next thought:

If we're using <country>, what's our policy with regards to nationstates collapsing, or controversial borders? It's an edge case, but I'm trying to think ahead.

Crimea or Palestine could easily be sensitive topics.

**Comment by ansuz** [comment]
Since there were no objections, I changed `location.country` in the nodeinfo.json spec to location.continent.

The spec can be found [here](https://github.com/hyperboria/docs/blob/master/cjdns/nodeinfo-json.md).

Repo structure should ∴ be `/creds/<continent code>/<region>/yourNodesPublicKey.k`.

**Comment by tomymartingrinberg-cpu** [comment]
Hi, I'm setting up a cjdns node on Windows and I need a public peer to connect to Hyperboria.
OS: Windows 10/11. Purpose: testing/learning.
Could anyone share a public peer (cjdns IPv6 + password)? Example:
fcec:abcd:1234:...  password: Example123
Thanks!
