### ISSUE TITLE
uniaikratom down

### ISSUE THREAD

**Issue by kpcyrd** [hyperboria/peers#104]
@kyrias your [peer](https://github.com/hyperboria/peers/blob/master/eu/fr/paris/kratom.random.sh.k) seems to be down, please look into that. :)

The comment says it's going to expire during november 2016 (which was quite a while ago).

**Comment by kyrias** [comment]
Not my peer, and the person who added it doesn't have a GitHub account associated with that email, hm.

**Comment by kpcyrd** [comment]
Are you ok with removing it? :)

**Comment by kyrias** [comment]
I don't see why not ;)
