### ISSUE TITLE
four peers unresponsive.

### ISSUE THREAD

**Issue by janicez** [hyperboria/peers#122]
v0.0000.0000.0000.001b.mh9m0411cfcg7xhdc8n6ckls1tjgnvvbdfzdgqf5196tfkw96rr0.k UNRESPONSIVE in 0kb/s out 0kb/s "igel-losangeles"
v0.0000.0000.0000.0019.6d2kt2hbcp7v0pw9q6f1u2s039kfnt4m4123rjxg26hsgrc12v80.k UNRESPONSIVE in 0kb/s out 0kb/s "salesforce-tower"
v0.0000.0000.0000.0017.ppj4n90uw68nvtmz7hz4g1ksubsxylgbhqg9p9x6f37vp4s599c0.k UNRESPONSIVE in 0kb/s out 0kb/s "kylers-awesome-website"
v0.0000.0000.0000.0013.q5nhj9kg6ddmk571jb259mct2ljd10z9xvyf05y3hu66wk4qnk20.k UNRESPONSIVE in 0kb/s out 0kb/s "outer" (weuxel)

**Comment by wfleurant** [comment]
node `igel-losangeles` evidently over bandwidth -- negotiating price over the weekend..
