### ISSUE TITLE
Are there peers which use port in 1-999?

### ISSUE THREAD

**Issue by eret1k** [hyperboria/peers#127]
I use a mobile Internet and the provider cuts the connection speed on all ports after 999

**Comment by iczero** [comment]
Isn't that a violation of the net neutr--oh those don't exist anymore.
Right.

**Comment by eret1k** [comment]
In Russia this rule "provider cuts the connection speed on all ports after 999" exist.

**Comment by FinlayDaG33k** [comment]
There *might* be some peers that use port 1-999, but those are probably really rare since those ports are often used for other things as well.
Mobile Internet isn't the fastest anyways.
