### ISSUE TITLE
IPs vs Hostnames?

### ISSUE THREAD

**Issue by thefinn93** [hyperboria/peers#23]
Do we prefer IPs or DNS hostnames? or do we care? If we do, we should update tests.py to reflect that.

**Comment by Kubuxu** [comment]
I think we should prefer IPs.

**Comment by ansuz** [comment]
One more for IPs.

**Comment by thefinn93** [comment]
So prefer (but not require) IPs?

**Comment by kpcyrd** [comment]
@thefinn93 +1

**Comment by kylerschin** [comment]
prefer ip but not require. But then again.... people change ips....

**Comment by ansuz** [comment]
in [this duplicate issue (oops)](https://github.com/hyperboria/peers/issues/50) we've generally agreed (though only among 3 people who run public peers) that public peers should probably be restricted to nodes with static IPs.

Two reasons:

## one

_prefer_ is a really vague verb that we can't really enforce (via tests), so it's especially worthwhile to have a policy of preferring.

## two

Static IPs are a barrier to entry for public node operators wanting to host their credentials _in this repository_. I'm more interested in lowering the barrier to entry for new users.

DNS is one more thing that can fail, and these peers are here as a service for those looking to join the network, who are generally less experienced at troubleshooting a cjdns node.
