### ISSUE TITLE
add requirements for json to README

### ISSUE THREAD

**Issue by ansuz** [hyperboria/peers#3]
1. Creds should be valid json (no comments).
2. Creds should not be so long that they [overflow](https://github.com/hyperboria/docs/blob/master/bugs/connectTo-overflow.md) (we need a linter)
3. The json should have required fields. Obviously `publicKey` and `password`, but also:
  + location
  + contact
4. Path must adhere to the repository layout. That means keeping a consistent hierarchy for folders.
5. ???

**Comment by ansuz** [comment]
tabs or spaces? It should match cjdroute.conf

**Comment by dansup** [comment]
I think tabs.

**Comment by kpcyrd** [comment]
I think there needs to be an example what valid json is, since most people don't exchange valid json for peering ->

```
"ip:port":{ ... }
```

if the spec is "one line, regular peering format" we could just concat all files, which is what I've planned for nightfall.

**Comment by ansuz** [comment]
http://jsonlint.com/

**Comment by ansuz** [comment]
we need an extra step to validate that it will fit within a datagram after bencoding. Too much json will crash the configurator.

**Comment by kpcyrd** [comment]
#2 is invalid on jsonlint.com
