### ISSUE TITLE
re: decentralization

### ISSUE THREAD

**Issue by ansuz** [hyperboria/peers#5]
A common convention for organizing public peering credentials is a step towards the goal of making cjdns easier to configure for the first time. 

That being said, keeping the credentials in this repository where a set of gatekeepers can add or remove files centralizes an important aspect of cjdns (who connects with whom).

I'm considering creating a reference implementation that can scrape this repository, or another repository with the same structure. The conventions that make that possible should be agreed upon (indexing via html? keeping a json index?).

@kpcyrd, I expect you'll be interested in this because of [yrd](https://github.com/kpcyrd/yrd) and [nightfall](https://github.com/kpcyrd/nightfall).

@clehner Maybe we can tie this in with [nij](https://github.com/clehner/nij), generating a nodeinfo.json file in accordance with commonly agreed on location data, and then read nodeinfo.json when looking for nearby peers (programatically)?

**Comment by ansuz** [comment]
I added a [js-api](https://github.com/hyperboria/peers/#javascript-api) that should work for any project with the same structure.

Maybe this could be used to provide an http api? Search for nodes by region?

**Comment by kpcyrd** [comment]
If we're exposing this as an api, it would be interesting to have something tag based. For example have a script that connects to some cjdns nodes running in the same data centre, which is often free traffic.

**Comment by ansuz** [comment]
@lgierth pointed out that the configurator now only sends data which will be used by cjdroute, so we're less limited in terms of how much data we want to put into the credentials.

What would we name a field like that?

**Comment by wfleurant** [comment]
- circuit
- noc
- vps
- hosting
- backbone

**Comment by kylerschin** [comment]
technically, if enough nodes are added, is it decentralized? @ansuz @kpcyrd @wfleurant

**Comment by ansuz** [comment]
I just work here man

**Comment by kylerschin** [comment]
@ansuz I'm gonna make you very :smile: .... YOUR FIRED!

**Comment by ansuz** [comment]
![youre](https://user-images.githubusercontent.com/1264398/28238814-19114d8e-695c-11e7-8b69-56444051b6bc.jpg)

**Comment by kylerschin** [comment]
@ansuz It was intentional, as someone as dumb as Donald J. Trump himself will never have correct grammar. It's exaggerated in all the YouTube Videos. Oh wait, your too old. Or I'm too young. (13)

**Comment by ansuz** [comment]
![twas-merely-a-jest](https://user-images.githubusercontent.com/1264398/28239057-e459a1c0-6962-11e7-837d-43f6a427d13c.jpg)
