### ISSUE TITLE
hype.jazzanet.com.k is down

### ISSUE THREAD

**Issue by vrde** [hyperboria/peers#51]
@thefinn93 do you know something about it ~Kubuxu

**Comment by thefinn93** [comment]
Not mine

**Comment by thefinn93** [comment]
According to the blame log, it belongs to @jaythespacehound

**Comment by Kubuxu** [comment]
Or right, I checked who modified it (and you modified all the files while doing the reformat). Sorry for that.

**Comment by jaythespacehound** [comment]
Sorry guys, I moved countries and looks like it didn't come back up by itself when the server restarted itself. Should be up again.

**Comment by ansuz** [comment]
Hi @jaythespacehound, glad you're back.

Systemd is probably the most modern way to keep a cjdroute service running, but I've had good results with a crontab (as root)

`* * * * * pidof cjdroute || fc00`

Thanks for the update.
