### ISSUE TITLE
Misleading Geo Location - gel-california.usa.k acually florida

### ISSUE THREAD

**Issue by kylerschin** [hyperboria/peers#52]
when tested IP, the location reads West Palm Beach, Florida. Please rename the address.

**Comment by ansuz** [comment]
for reference: [this one](https://github.com/hyperboria/peers/blob/master/NA/us/california/igel-california.usa.k).

ping @wfleurant

**Comment by thefinn93** [comment]
When you say "tested", do you mean run it against some random geo IP database? You know those are aren't always right.... right?

Ping time is consistent it be being in Los Angeles, CA:

From Los Angeles, CA:
```
--- 192.169.7.142 ping statistics ---
17 packets transmitted, 17 received, 0% packet loss, time 16007ms
rtt min/avg/max/mdev = 0.556/0.755/0.904/0.089 ms
```

From Seattle, WA:
```
--- 192.169.7.142 ping statistics ---
63 packets transmitted, 63 received, 0% packet loss, time 62082ms
rtt min/avg/max/mdev = 34.343/37.891/51.437/2.674 ms
```

From New York City, NY:
```
--- 192.169.7.142 ping statistics ---
70 packets transmitted, 70 received, 0% packet loss, time 69084ms
rtt min/avg/max/mdev = 66.874/66.976/67.189/0.240 ms
```

From San Francisco, CA:
```
--- 192.169.7.142 ping statistics ---
15 packets transmitted, 15 received, 0% packet loss, time 14020ms
rtt min/avg/max/mdev = 11.340/11.431/11.640/0.154 ms
```

**Comment by wfleurant** [comment]
The physical location of the node is Los Angeles, CA.
