### ISSUE TITLE
Redo README.md

### ISSUE THREAD

**Issue by ansuz** [hyperboria/peers#6]
I wrote it off the top of my head, and would like some input.

**Comment by Kubuxu** [comment]
Sample json is missing `contact` field and requirement of using `.k` extension is missing.

**Comment by Kubuxu** [comment]
Contact field is now mentioned but structure of readme is just weird. nodeinfo has really almost nothing to do with data in this repo.

```
15:12 <@mk-fg> Also, I find structure of that document utterly confusing
...
15:15 <@mk-fg> Still, saying something like "this repo is a list of public peer credentials, which can be added here (in Nodeinfo.json format) by anyone via github PR" is like one sentence totally tying it all together
```

**Comment by Kubuxu** [comment]
To add: `format is: valid JSON, space after colon, indentation using 4 spaces`.

**Comment by ansuz** [comment]
[added the .k requirement](https://github.com/hyperboria/peers/commit/41d4682c8a3caed1bb300c4c1a38f01a6c95ee7f)

**Comment by ansuz** [comment]
added formatting specifications to the readme

**Comment by ansuz** [comment]
It could still be improved, but I'm gonna close this anyway.
