### ISSUE TITLE
accept ipv6 peers?

### ISSUE THREAD

**Issue by kylerschin** [hyperboria/peers#62]
if the clearnet goes down.... we can't resolve ipv4. and since we cant use domains and our ipv4 addresses keep changing, can we use ipv6 instead? why can't we ditch ipv4 peering? that way we can still peer with each other if the clearnet goes down.

**Comment by kylerschin** [comment]
i know that clearnet goes down is impossable, but many contries are cut off entirely by censorship. even my city has slow internet and my current project uses drones with OPEN-WRT / COMMOTION / CJDNS on them to communicate. so far it works. but we cant use ipv4 for that. we cant use ipv4 forever.

**Comment by kylerschin** [comment]
# PLEASE GET Ipv6!!!!!!!!!!!

**Comment by wfleurant** [comment]
sure.. which country would you prefer?

**Comment by kpcyrd** [comment]
@kylerschin IPv6 peers are accepted in this repo, feel free to contribute any. There are also people on irc.fc00.io/#peering who are able to provide ipv6 peering.

**Comment by ansuz** [comment]
ditching ipv4 peering still isn't an option with many ISPs. Some day soon, hopefully.

**Comment by wfleurant** [comment]
@kylerschin does irvinca-usa.k have IPv6? I have a ~150ms from Cali to Europe if you are interested we can peer.

**Comment by wfleurant** [comment]
@kylerschin also -- there's an IPv6 in CA, USA so ~10ms from you.. cheers.
