### ISSUE TITLE
create json linter

### ISSUE THREAD

**Issue by ansuz** [hyperboria/peers#7]
jsonlint.com isn't quite what we need, since credentials would all need to be wrapped in curly braces to be considered valid.

Putting this on a github.io page with a textarea field and some buttons would be sufficient.

```javascript
try{
    JSON.parse("{"+theirJSON+"}");
}catch(err){
    /* you messed up */
}
```

**Comment by kpcyrd** [comment]
I'm doing the same [here][1]. I'm then iterating over all keys in that dict.

[1]: https://github.com/kpcyrd/yrd/blob/master/yrd/peer.py#L97
