### ISSUE TITLE
EU/ru/moscow/h.bunjlabs.com.k

### ISSUE THREAD

**Issue by SEVENID** [hyperboria/peers#74]
Now (UTC 2016-09-18 20:30:00) cjdns peer EU/ru/moscow/h.bunjlabs.com.k is offline. Please recheck it and, if approved, delete.

**Comment by ansuz** [comment]
Thanks for noticing.

@Show-vars, it seems this is your node, correct? Can you confirm?

**Comment by kyrias** [comment]
It's still down a month later, so I suggest we nuke it.

**Comment by Show-vars** [comment]
I'm so sorry about that. On this server we have been made a lot of changes and probably something was broken. I'm recently update the cjdns software and now `h.bunjlabs.com` became available.

**Comment by ansuz** [comment]
Thanks!

**Comment by SEVENID** [comment]
Offline more than a day. Again.

**Comment by kyrias** [comment]
@Show-vars ?
