### ISSUE TITLE
Add Transatlantic Peering Network

### ISSUE THREAD

**Issue by jimenezrick** [hyperboria/peers#75]
The list of peers is in here:

http://web.transatlantic.h-ic.eu/

**Comment by ansuz** [comment]
Pull requests welcome :)

**Comment by ProgVal** [comment]
wtf
```
$ host transatlantic-northeurope.cloudapp.net
transatlantic-northeurope.cloudapp.net has address 0.0.0.0
```

**Comment by ansuz** [comment]
I can't ping any of these nodes, so I'm gonna go ahead and close this.

**Comment by ProgVal** [comment]
I am connected to transatlantic-westeurope.
