### ISSUE TITLE
make continent codes lower case

### ISSUE THREAD

**Issue by ansuz** [hyperboria/peers#79]
...because everything else is lower case, and it would make querying the repo quite a bit simpler.

**Comment by Sireeni** [comment]
oh and maybe indicate `"/1/location/<continent code>"` instead of `"/1/location/<continent>"` (which leads to type `/1/location/europe` instead of `/1/location/eu`)? :D

**Comment by ansuz** [comment]
@Sireeni wrong repo.

You want https://github.com/fc00/peers-api

This is just where the data comes from.
